# Generated by Django 4.0 on 2023-11-27 20:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='choice',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='name', unique=True),
        ),
    ]
