# Generated by Django 4.0 on 2023-11-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_rename_choice_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
