# Generated by Django 4.0 on 2023-11-28 20:40

from django.db import migrations
import django.db.models.deletion
import select2.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_remove_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='choice',
            field=select2.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.category'),
        ),
    ]
